### ISSUE TITLE
how do you run the update report?

### ISSUE THREAD

**Issue by fommil** [JetBrains/sbt-structure#32]
In ensime-sbt we invoke the sbt update and updateClassifiers report for each Project and it is cronically slow (an hour for my work project).

I'm guessing you have a similar problem in sbt-structure.

I'm trying to work around this by constructing the aggregated reports (which seems to be faster when I type `update` in the CLI) and then querying it. However, I don't know how to programmatically call the aggregate report. Do you do this? Any hints appreciated.

http://stackoverflow.com/questions/33988388

**Comment by dancingrobot84** [comment]
@fommil Yes, that's a longstanding issues which we haven't solved yet completely.

As far as I get it, by "aggregated reports" you mean the output of `update` command executed in SBT REPL. Unfortunately, comparing `update` in REPL and `update` on each project is not correct because the first one runs only on root project and its dependents/aggregates, thus it would not collect information about library dependencies for projects that are not reachable from the root project of the root build. So, to get complete information about library dependencies of each project you need to call `update` on each project. I'd like to cast here @eed3si9n and @jsuereth to either confirm or fix my words.

Now, after peeking at ensime-sbt's code, I would say that you have the same problem that we had until version 5.0.0 of sbt-structure: ensime-sbt operates directly on `sbt.State`. Therefore you can't use caching and parallelization facilities of SBT and, without them, execution of tasks (`update` in particular) is slower since they are executed sequentially and do not reuse results from their previous execution. Please note, that it does not have any impact on settings since they are static, but tasks are dynamic.

We solved this particular problem by changing the way we operate: instead of extracting information directly from `sbt.State`, we depend on SBT's tasks. For example, take a look at [this file](https://github.com/JetBrains/sbt-structure/blob/master/extractor/src/main/scala/org/jetbrains/sbt/extractors/RepositoryExtractor.scala#L67). It's a bit complex, but I think it should express the idea well. 

I did speed comparison between sbt-structure 4.3.2 and 5.0.0 and it is clear that 5.0.0 is faster, from seconds on quite simple projects (10-20 subprojects, inter-dependencies are sparse) to **minutes** (100+ subprojects, highly interdependent).

**Comment by fommil** [comment]
@dancingrobot84 thanks for responding! is good to hear that you have something. The ENSIME approach is becoming prohibitively slow and takes at hour on my work project. Fyi this is my WIP https://github.com/ensime/ensime-sbt/pull/122

Where in your code sold I start looking, e.g. for where you call the cacheable code? (Also, I hope it's not so fragile that the version of SBT matters)

**Comment by fommil** [comment]
sold = so I can

**Comment by dancingrobot84** [comment]
@fommil Take a look at [CreateTasks.scala](https://github.com/JetBrains/sbt-structure/blob/master/extractor/src/main/scala/org/jetbrains/sbt/CreateTasks.scala) first. That is where we initialize our own tasks that depend on SBT tasks. `extractRepository` is the task that calls `update` and `updateClassifier`; its definition is in [RepositoryExtractor.scala](https://github.com/JetBrains/sbt-structure/blob/master/extractor/src/main/scala/org/jetbrains/sbt/extractors/RepositoryExtractor.scala#L69), in `RepositoryExtractor.taskDef` function.

If you'd like, we can arrange a Skype call and I will explain you sbt-structure's internals in detail.

**Comment by fommil** [comment]
@dancingrobot84 thanks, I might take you up on that offer! I'm UK based and only available to chat in evenings and weekends.

**Comment by fommil** [comment]
@dancingrobot84 you might get a minor performance improvement by avoiding the lazy View of `.mapValues` here https://github.com/JetBrains/sbt-structure/blob/master/extractor/src/main/scala/org/jetbrains/sbt/extractors/RepositoryExtractor.scala#L84

**Comment by fommil** [comment]
@dancingrobot84 Thank you thank you thank you! I have something running now that seems faster.

I've still got a few functional kinks to iron out, but this gets the time down from 1m:20s to 1m when run on `ensime-server` itself. I hope this will be more dramatic for larger projects.

**Comment by dancingrobot84** [comment]
@fommil :+1:
